//var mapboxgl = window.mapboxgl = window.mapboxgl ||require('@mapgis/mapbox-gl.js');  //开发过程中调试源码可用，其他情况下直接用下面的源码编译
//var mapboxgl = window.mapboxgl = window.mapboxgl || require('@mapgis/mapbox-gl.js');
// var mapboxgl = window.mapboxgl = window.mapboxgl ||require('mapbox-gl');

import { MapExtend } from '../../mapboxgl/MapExtend'

export { MapExtend }

import {
    mapboxgl,
    MapDocLayer,
    MapTileLayer,
    MapWmsLayer,
    MapWMTSLayer,
    MapVectorLayer,
    ArcGISLayer,
    TDTLayer
} from '../../mapboxgl/layer';

export {
    mapboxgl,
    MapDocLayer,
    MapTileLayer,
    MapWmsLayer,
    MapWMTSLayer,
    MapVectorLayer,
    ArcGISLayer,
    TDTLayer
};

import {
    ServiceBase
} from '../../service/ServiceBase';

import {
    AnyLine,
    Arc,
    Zondy,
    CAttStruct,
    CAttDataRow,
    CDisplayStyle,
    CDisplayStyleExtend,
    CDynNoteInfo,
    CGDBInfo,
    Circle,
    CLineInfo,
    CPointInfo,
    CRegionInfo,
    DynNoteLableType,
    DynShowStyle,
    XClsType,
    VectClsType,
    FeatureType,
    FontShape,
    LabelLinType,
    LabelRegType,
    LabelPntType,
    RepeatType,
    LabelSpreadType,
    LineConstrain,
    EightDirType,
    ISShowArc,
    NetAnalyType,
    NetElemType,
    CLinAdjustType,
    CLinHeadType,
    CLinJointType,
    CLinStyleMakeType,
    CItemType,
    MapType,
    LayerStatusType,
    Feature,
    FeatureGeometry,
    FeatureGraphicBase,
    FeatureSet,
    GLine,
    GPoint,
    GRegion,
    LabelLinInfo,
    LabelRegInfo,
    LablePntInfo,
    MultiPolygon,
    Point2D,
    Polygon,
    PolyLine,
    Rectangle,
    Tangram,
    VectCls,
    WebGraphicsInfo,
    extend,
    isArray,
    extendDeep,
    copy,
    copyExcluce,
    reset,
    getElement,
    isElement,
    removeItem,
    indexOf,
    modifyDOMElement,
    applyDefaults,
    getParameterString,
    getWFParameterString,
    urlAppend,
    getParameters,
    IS_GECKO,
    Browser,
    getBrowser,
    isSupportCanvas,
    supportCanvas,
    isInTheSameDomain,
    toJSON,
    transformResult,
    copyAttributes,
    copyAttributesWithClip,
    cloneObject,
    newGuid,
    bind,
    bindAsEventListener,
    getTopAnalysisResult,
    ChineseToUtf8,
    DeepMerge,
    merge,
    mixin
} from '../../service/common';

import {
    ContourNoteParam,
    ContourParam,
    ContourZValue,
    ContourRegionInfo,
    MeshingParam,
    NetAnalyse,
    NetAnalysisExtent,
    SlopLineParam
} from '../../service/extend';

import {
    CommonServiceBase,
    Events,
    CORS,
    RequestTimeout,
    FetchRequest,
    IgsServiceBase,
    JSONFormat
} from '../../service/baseserver';

import {
    ColorInfo,
    GDBInfo,
    MapDoc,
    CatalogService,
    TileLayer,
    VectorLayer
} from '../../service/MRCS';

import {
    EditDocFeature,
    EditLayerFeature,
    EditServiceBase,
    MultiGeoQuery,
    MultiGeoQueryParameter,
    ObjClsQuery,
    ObjClsQueryParameter,
    QueryByLayerParameter,
    QueryDocFeature,
    QueryFeatureRule,
    QueryFeatureStruct,
    QueryLayerFeature,
    QueryParameter,
    QueryParameterBase,
    QueryServiceBase
} from '../../service/MRFS';

import {
    AnalysisBase,
    ClassBufferBase,
    ClassBufferByMultiplyRing,
    ClassBufferBySingleRing,
    ClipBase,
    ClipByCircle,
    ClipByLayer,
    ClipByPolygon,
    ContourAnalyse,
    FeatureBuffBase,
    FeatureBuffByMultiplyRing,
    FeatureBuffBySingleRing,
    NetAnalysis,
    OverlayBase,
    OverlayByLayer,
    OverlayByPolygon,
    ProjectBase,
    ProjectByLayer,
    ProjectBySRID
} from '../../service/MRFWS';

import {
    CalArea,
    CalPolyLineLength,
    CalServiceBase,
    CProjectBySRSID,
    CProjectParam,
    GeometryAnalysisBase,
    ProjectDots,
    ProjectRang,
    Smooth,
    TopAnalysis
} from '../../service/MRGS';

import {
    GetDocImageService,
    GetLayerImageService,
    GetMapImageService,
    GetMapInfoService,
    GetTileImageService,
    MapServiceBase
} from '../../service/MRMS';

import {
    CAllOtherDataItemInfoSource,
    CAnnInfo,
    CChartLabelFormat,
    CChartTheme,
    CChartThemeInfo,
    CChartThemeRepresentInfo,
    CChartType,
    CDotDensityTheme,
    CFourColorTheme,
    CGraduatedSymbolTheme,
    CLinInfo,
    CMultiClassTheme,
    CPntInfo,
    CRandomTheme,
    CRangeTheme,
    CRangeThemeInfo,
    CRegInfo,
    CSimpleTheme,
    CTheme,
    CThemeInfo,
    CUniqueTheme,
    CUniqueThemeInfo,
    ExpInfo,
    FolderInfo,
    FolderInfoAttribute,
    ItemValue,
    ThemeOper,
    ThemesInfo
} from '../../service/theme';

import {
    GeoFeatureThemeLayer,
    //ThemeFeature,
    //themeFeature,
    ThemeLayer,
    RangeThemeLayer,
    rangeThemeLayer,
    UniqueThemeLayer,
    GraphThemeLayer,
    graphThemeLayer,
    RandomThemeLayer,
    SimpleThemeLayer,
    RankSymbolThemeLayer,
    ThemeStyle,
    Theme3DLayer,
    RangeTheme3DLayer,
    rangeTheme3DLayer,
    UniqueTheme3DLayer,
    uniqueTheme3DLayer
} from '../../mapboxgl/theme';

export {
    GeoFeatureThemeLayer,
    // ThemeFeature,
    // themeFeature,
    ThemeLayer,
    RangeThemeLayer,
    rangeThemeLayer,
    UniqueThemeLayer,
    GraphThemeLayer,
    graphThemeLayer,
    RandomThemeLayer,
    SimpleThemeLayer,
    RankSymbolThemeLayer,
    ThemeStyle,
    Theme3DLayer,
    RangeTheme3DLayer,
    rangeTheme3DLayer,
    UniqueTheme3DLayer,
    uniqueTheme3DLayer
};

import {
    Bar,
    Bar3D,
    OverlayCircle,
    Graph,
    Line,
    Pie,
    OverlayPoint,
    RankSymbol,
    Ring,
    ThemeVector,
    ShapeFactory,
    ShapeParameters,
    FeatureCircle,
    Image,
    Label,
    FeatureLine,
    Point,
    FeaturePolygon,
    FeatureRectangle,
    Sector,
    FeatureTheme,
    // Bounds,
    // Collection,
    // Curve,
    // Geometry,
    // GeoText,
    // LinearRing,
    // LineString,
    // LonLat,
    // MultiLineString,
    // MultiPoint,
    // GeometryMultiPolygon,
    // Pixel,
    // GeometryPoint,
    // GeometryPolygon,
    // GeometryRectangle,
    // Size,
    // GeometryFeature,
    // GeometryVector,
    LevelRenderer,
    Render,
    Animation,
    Animator,
    Area,
    Clip,
    Color,
    ComputeBoundingBox,
    Config,
    LevelRendererCurve,
    Easing,
    Env,
    LevelRendererEvent,
    Eventful,
    Group,
    Handler,
    Http,
    Math,
    Matrix,
    Painter,
    PaintLayer,
    Shape,
    SmicBrokenLine,
    SmicCircle,
    SmicEllipse,
    SmicImage,
    SmicIsogon,
    SmicPoint,
    SmicPolygon,
    SmicRectangle,
    SmicRing,
    SmicSector,
    SmicStar,
    SmicText,
    Storage,
    Transformable,
    Util,
    LevelRendererVector,
    SUtil
} from '../../overlay';

export {
    Bar,
    Bar3D,
    OverlayCircle,
    Graph,
    Line,
    Pie,
    OverlayPoint,
    RankSymbol,
    Ring,
    ThemeVector,
    ShapeFactory,
    ShapeParameters,
    FeatureCircle,
    Image,
    Label,
    FeatureLine,
    Point,
    FeaturePolygon,
    FeatureRectangle,
    Sector,
    FeatureTheme,
    // Bounds,
    // Collection,
    // Curve,
    // Geometry,
    // GeoText,
    // LinearRing,
    // LineString,
    // LonLat,
    // MultiLineString,
    // MultiPoint,
    // GeometryMultiPolygon,
    // Pixel,
    // GeometryPoint,
    // GeometryPolygon,
    // GeometryRectangle,
    // Size,
    // GeometryFeature,
    // GeometryVector,
    LevelRenderer,
    Render,
    Animation,
    Animator,
    Area,
    Clip,
    Color,
    ComputeBoundingBox,
    Config,
    LevelRendererCurve,
    Easing,
    Env,
    LevelRendererEvent,
    Eventful,
    Group,
    Handler,
    Http,
    Math,
    Matrix,
    Painter,
    PaintLayer,
    Shape,
    SmicBrokenLine,
    SmicCircle,
    SmicEllipse,
    SmicImage,
    SmicIsogon,
    SmicPoint,
    SmicPolygon,
    SmicRectangle,
    SmicRing,
    SmicSector,
    SmicStar,
    SmicText,
    Storage,
    Transformable,
    Util,
    LevelRendererVector,
    SUtil
};


export {
    ServiceBase
};


export {
    AnyLine,
    Arc,
    Zondy,
    CAttStruct,
    CAttDataRow,
    CDisplayStyle,
    CDisplayStyleExtend,
    CDynNoteInfo,
    CGDBInfo,
    Circle,
    CLineInfo,
    CPointInfo,
    CRegionInfo,
    DynNoteLableType,
    DynShowStyle,
    XClsType,
    VectClsType,
    FeatureType,
    FontShape,
    LabelLinType,
    LabelRegType,
    LabelPntType,
    RepeatType,
    LabelSpreadType,
    LineConstrain,
    EightDirType,
    ISShowArc,
    NetAnalyType,
    NetElemType,
    CLinAdjustType,
    CLinHeadType,
    CLinJointType,
    CLinStyleMakeType,
    CItemType,
    MapType,
    LayerStatusType,
    Feature,
    FeatureGeometry,
    FeatureGraphicBase,
    FeatureSet,
    GLine,
    GPoint,
    GRegion,
    LabelLinInfo,
    LabelRegInfo,
    LablePntInfo,
    MultiPolygon,
    Point2D,
    Polygon,
    PolyLine,
    Rectangle,
    Tangram,
    VectCls,
    WebGraphicsInfo,
    extend,
    isArray,
    extendDeep,
    copy,
    copyExcluce,
    reset,
    getElement,
    isElement,
    removeItem,
    indexOf,
    modifyDOMElement,
    applyDefaults,
    getParameterString,
    getWFParameterString,
    urlAppend,
    getParameters,
    IS_GECKO,
    Browser,
    getBrowser,
    isSupportCanvas,
    supportCanvas,
    isInTheSameDomain,
    toJSON,
    transformResult,
    copyAttributes,
    copyAttributesWithClip,
    cloneObject,
    newGuid,
    bind,
    bindAsEventListener,
    getTopAnalysisResult,
    ChineseToUtf8,
    DeepMerge,
    merge,
    mixin
};
export {
    ContourNoteParam,
    ContourParam,
    ContourZValue,
    ContourRegionInfo,
    MeshingParam,
    NetAnalyse,
    NetAnalysisExtent,
    SlopLineParam
};
export {
    CommonServiceBase,
    Events,
    CORS,
    RequestTimeout,
    FetchRequest,
    IgsServiceBase,
    JSONFormat
};
export {
    ColorInfo,
    GDBInfo,
    MapDoc,
    CatalogService,
    TileLayer,
    VectorLayer
};
export {
    EditDocFeature,
    EditLayerFeature,
    EditServiceBase,
    MultiGeoQuery,
    MultiGeoQueryParameter,
    ObjClsQuery,
    ObjClsQueryParameter,
    QueryByLayerParameter,
    QueryDocFeature,
    QueryFeatureRule,
    QueryFeatureStruct,
    QueryLayerFeature,
    QueryParameter,
    QueryParameterBase,
    QueryServiceBase
};
export {
    AnalysisBase,
    ClassBufferBase,
    ClassBufferByMultiplyRing,
    ClassBufferBySingleRing,
    ClipBase,
    ClipByCircle,
    ClipByLayer,
    ClipByPolygon,
    ContourAnalyse,
    FeatureBuffBase,
    FeatureBuffByMultiplyRing,
    FeatureBuffBySingleRing,
    NetAnalysis,
    OverlayBase,
    OverlayByLayer,
    OverlayByPolygon,
    ProjectBase,
    ProjectByLayer,
    ProjectBySRID
};
export {
    CalArea,
    CalPolyLineLength,
    CalServiceBase,
    CProjectBySRSID,
    CProjectParam,
    GeometryAnalysisBase,
    ProjectDots,
    ProjectRang,
    Smooth,
    TopAnalysis
};
export {
    GetDocImageService,
    GetLayerImageService,
    GetMapImageService,
    GetMapInfoService,
    GetTileImageService,
    MapServiceBase
};
export {
    CAllOtherDataItemInfoSource,
    CAnnInfo,
    CChartLabelFormat,
    CChartTheme,
    CChartThemeInfo,
    CChartThemeRepresentInfo,
    CChartType,
    CDotDensityTheme,
    CFourColorTheme,
    CGraduatedSymbolTheme,
    CLinInfo,
    CMultiClassTheme,
    CPntInfo,
    CRandomTheme,
    CRangeTheme,
    CRangeThemeInfo,
    CRegInfo,
    CSimpleTheme,
    CTheme,
    CThemeInfo,
    CUniqueTheme,
    CUniqueThemeInfo,
    ExpInfo,
    FolderInfo,
    FolderInfoAttribute,
    ItemValue,
    ThemeOper,
    ThemesInfo
};

// 大数据相关
import {
    EchartsLayer,
    MapvLayer,
    DeckglLayer,
    /* StreamLayer */
} from '../../mapboxgl/overlay/index.js'

export {
    EchartsLayer,
    MapvLayer,
    DeckglLayer,
    /* StreamLayer */
}



