var config = {
    name: "",
    title: "MapGIS WebClinet-Cesium帮助文档",
    mapmode: "cesium",
    childs: [{
            name: "几何图元",
            materialicon: "bubble_chart",
            folder: "geometry",
            leaffolder: false,
            childs: [{
                name: "通用几何GeoJSON",
                materialicon: "bubble_chart",
                folder: "geojson",
                leaffolder: true,
                childs: [{
                    name: "Point",
                    file: "point",
                    diffcult: "1",
                    detail: "给定一个geojson格式的经纬坐标点，将其展示在cesium上。",
                    icon: "point.png",
                    mardown: "E01GeoPoint.md",
                    update: "最后更新时间：2018-05-10"
                }, {
                    name: "Line",
                    file: "line",
                    diffcult: "1",
                    detail: "将地理位置的坐标数组(二维)以geojson格式加载进cesium。",
                    icon: "line.png",
                    mardown: "E01GeoPoint.md",
                    update: "最后更新时间：2018-05-10"
                }, {
                    name: "Polygon",
                    file: "polygon",
                    diffcult: "1",
                    detail: "一个环形坐标数组的数组(三维)以geojson格式加载进cesium。针对“带洞区”，最好采取外圈顺时针，内圈逆时针的方式",
                    icon: "polygon.png",
                    mardown: "E01GeoPoint.md",
                    update: "最后更新时间：2018-05-10"
                }, {
                    name: "MultiPoint",
                    file: "multipoint",
                    diffcult: "1",
                    detail: "将位置坐标组成二维数组以geojson格式加载进leafelt中。",
                    icon: "multipoint.png",
                    mardown: "E01GeoPoint.md",
                    update: "最后更新时间：2018-05-10"
                }, {
                    name: "MultiLine",
                    file: "multiline",
                    diffcult: "1",
                    detail: "将线坐标数组的数组(三维)以geojson格式加载进cesium。",
                    icon: "multiline.png",
                    update: "最后更新时间：2018-05-10"
                }, {
                    name: "MultiPolygon",
                    file: "multipolygon",
                    diffcult: "2",
                    detail: "将面坐标数组的数组(四维)以geojson格式加载进cesium。",
                    icon: "multipolygon.png",
                    update: "最后更新时间：2018-05-10"
                }, {
                    name: "FeatureCollection",
                    file: "featurecollection",
                    diffcult: "2",
                    detail: "以Geojson特征集合数据格式将数据加载进cesium。",
                    icon: "featurecollection.png",
                    update: "最后更新时间：2018-05-10"
                }, {
                    name: "地理数据转换",
                    file: "transform",
                    diffcult: "2",
                    detail: "将特定或非特定格式的地理数据转换为标准的geojson格式加载进cesium。",
                    icon: "transform.png",
                    update: "最后更新时间：2018-05-10"
                }, {
                    name: "JsonParse",
                    file: "jsonparse",
                    diffcult: "2",
                    detail: "接受一个标准格式的JSON字符串，并返回解析后标准的JavaScript对象，可用于geojson数据的解析。",
                    icon: "jsonparse.png",
                    update: "最后更新时间：2018-05-10"
                }]
            }]
        },
        {
            name: "客户端可视化",
            materialicon: "camera",
            folder: "dataview",
            leaffolder: false,
            childs: [{
                name: "Mapv",
                materialicon: "camera",
                folder: "mapv",
                leaffolder: true,
                childs: [{
                    name: "DataSet",
                    file: "dataset",
                    diffcult: "1",
                    detail: "",
                    icon: "dataset.png",
                    update: "最后更新时间：2018-07-25"
                }, {
                    name: "Intensity",
                    file: "intensity",
                    diffcult: "1",
                    detail: "",
                    icon: "intensity.png",
                    update: "最后更新时间：2018-07-25"
                }, {
                    name: "Layer图层",
                    file: "layer",
                    diffcult: "1",
                    detail: "",
                    icon: "layer.png",
                    update: "最后更新时间：2018-07-25"
                }]
            }]
        },
        {
            name: "客户端空间分析",
            materialicon: "iso",
            folder: "analysis",
            leaffolder: true,
            childs: [{
                name: "缓冲区分析",
                file: "buffer",
                diffcult: "1",
                detail: "给定一个缓冲半径进行缓冲区分析. 单位支持 miles 米,kilometers 千米,degrees 度.",
                icon: "buffer.png",
                update: "最后更新时间：2018-05-05"
            }, {
                name: "泰森多边形分析",
                file: "voronoi",
                diffcult: "2",
                detail: "针对给定的点生成泰森多边形,请注意一定要传入外包矩形bbox参数",
                icon: "voronoi.png",
                update: "最后更新时间：2018-05-05"
            }, {
                name: "TIN三角网分析",
                file: "tin",
                diffcult: "1",
                detail: "TIN方法将无重复点的散乱数据点集按某种规则(如Delaunay 规则) 进行三角剖分，使这些散乱点形成连续但不重叠的不规则三角面片网，并以此来描述3D 物体的表面。",
                icon: "tin.png",
                update: "最后更新时间：2018-05-05"
            }, {
                name: "中心点提取",
                file: "centroid",
                diffcult: "1",
                detail: "计算给定GeoJSON的数据中心支持所有的GeoJSON类型",
                icon: "centroid.png",
                update: "最后更新时间：2018-05-05"
            }, {
                name: "插值分析",
                file: "along",
                diffcult: "1",
                detail: "线插值操作是通过 计算起点-终点长度,然后再根据长度等分计算需要插值的点,最后再把这些点插入到原始数据中.",
                icon: "along.png",
                update: "最后更新时间：2018-05-05"
            }]
        },
        {
            name: "实时数据分析Els",
            materialicon: "search",
            folder: "elasticsearch",
            leaffolder: true,
            childs: [{
                name: "首页",
                file: "index",
                diffcult: "1",
                detail: "",
                icon: "index.gif",
                update: "最后更新时间：2018-06-27,如有问题请咨询创新中心"
            }, {
                name: "聚合",
                file: "base",
                diffcult: "2",
                detail: "",
                icon: "base.gif",
                update: "最后更新时间：2018-06-27,如有问题请咨询创新中心"
            }, {
                name: "聚合用例",
                file: "aggsexamples",
                diffcult: "2",
                detail: "",
                icon: "aggsexamples.gif",
                update: "最后更新时间：2018-06-27,如有问题请咨询创新中心"
            }, {
                name: "地图操作基本概念",
                file: "gisbase",
                diffcult: "2",
                detail: "",
                icon: "gisbase.gif",
                update: "最后更新时间：2018-06-27,如有问题请咨询创新中心"
            }, {
                name: "官方接口",
                file: "command",
                diffcult: "2",
                detail: "",
                icon: "command.gif",
                update: "最后更新时间：2018-06-27,如有问题请咨询创新中心"
            }, {
                name: "中地接口",
                file: "webclient",
                diffcult: "2",
                detail: "",
                icon: "webclient.gif",
                update: "最后更新时间：2018-06-27,如有问题请咨询创新中心"
            }]
        }
    ]
};