var config = {
    name: "",
    title: "MapGIS WebClinet-MapboxGL演示网站",
    mapmode: "leaflet",
    childs: [{
            name: "官方教程",
            materialicon: "dashboard",
            folder: "offical",
            leaffolder: false,
            childs: [
                {
                    name: "官方教程",
                    materialicon: "dashboard",
                    folder: "tutorials",
                    leaffolder: true,
                    childs: [{
                        name: "leaflet快速上手指导",
                        file: "quickstart",
                        diffcult: "1",
                        detail: "此教程指导你快速开始leaflet的基础开发，包括设置一个leaflet地图、新建一个标志点、绘制线、弹出框以及事件处理。",
                        icon: "quickstart.png",
                        update: "最后更新时间：2018-05-12"
                    }, {
                        name: "移动端leaflet",
                        file: "mobile_leaflet",
                        diffcult: "1",
                        detail: "创建一个全屏地图，从而在移动设备中使用，例如iPhone、iPad或者Android手机。同时也将获得和使用用户当前的地理位置。",
                        icon: "mobile_leaflet.png",
                        update: "最后更新时间：2018-05-12"
                    }, {
                        name: "自定义图标标记",
                        file: "custom_icons",
                        diffcult: "1",
                        detail: "使用自定义的图标作为地图上的标注点。",
                        icon: "custom_icons.png",
                        update: "最后更新时间：2018-05-12"
                    }, {
                        name: "使用GeoJSON",
                        file: "geojson_leaflet",
                        diffcult: "1",
                        detail: "使用GeoJSON创建一个矢量图层，并与该图层进行交互",
                        icon: "geojson_leaflet.png",
                        update: "最后更新时间：2018-05-12"
                    }, {
                        name: "交互式分级统计地图",
                        file: "choropleth_map",
                        diffcult: "2",
                        detail: "创建一个色彩丰富可交互的分级统计地图，数据使用美国人口密度图（GeoJSON格式），并在网页中使用了一些自定义的地图控件。",
                        icon: "choropleth_map.png",
                        update: "最后更新时间：2018-05-12"
                    }, {
                        name: "图层分组和图层控制",
                        file: "groups_control",
                        diffcult: "1",
                        detail: "管理地图图层，并且使用图层切换控件轻松的切换地图上的不同图层。",
                        icon: "groups_control.png",
                        update: "最后更新时间：2018-05-12"
                    }, {
                        name: "缩放级别",
                        file: "zoom_levels",
                        diffcult: "1",
                        detail: "深入地了解缩放级别。",
                        icon: "zoom_levels.png",
                        update: "最后更新时间：2018-05-12"
                    }, {
                        name: "非地理地图",
                        file: "non_geographical_maps",
                        diffcult: "1",
                        detail: "主要是使用L.CRS.Simple，讲解在没有经纬度的概念下如何构建地图。",
                        icon: "non_geographical_maps.png",
                        update: "最后更新时间：2018-05-12"
                    }, {
                        name: "WMS和TMS",
                        file: "wms_tms",
                        diffcult: "1",
                        detail: "从专业地理信息系统中整合WMS和TMS服务。",
                        icon: "wms_tms.png",
                        update: "最后更新时间：2018-05-12"
                    }, {
                        name: "使用地图分层",
                        file: "map_panes",
                        diffcult: "1",
                        detail: "主要讲解如何使默认的地图分层显示在瓦片图层的顶部，并且如何覆盖它。",
                        icon: "map_panes.png",
                        update: "最后更新时间：2018-05-12"
                    }, {
                        name: "视频展示",
                        file: "show_video",
                        diffcult: "1",
                        detail: "leaflet可以帮助您在地图上的某个地方显示视频播放。",
                        icon: "show_video.png",
                        update: "最后更新时间：2018-05-12"
                    }]
                },
                {
                    name: "官方插件",
                    materialicon: "dashboard",
                    folder: "plugins",
                    leaffolder: true,
                    childs: [{
                        name: "leaflet.Draw",
                        file: "draw",
                        diffcult: "2",
                        detail: "leaflet的矢量绘图和编辑插件。",
                        icon: "draw.png",
                        update: "最后更新时间：2018-05-12"
                    }, {
                        name: "leaflet.FullScreen",
                        file: "fullscreen",
                        diffcult: "1",
                        detail: "leaflet的HTML5全屏插件。",
                        icon: "fullscreen.png",
                        update: "最后更新时间：2018-05-12"
                    }, {
                        name: "leaflet.Graticule",
                        file: "graticule",
                        diffcult: "1",
                        detail: "创建一个Canvas作为ImageOverlay来绘制经纬刻度，并在地图的边缘显示网格标记。",
                        icon: "graticule.png",
                        update: "最后更新时间：2018-05-12"
                    }, {
                        name: "leaflet.Editable",
                        file: "editable",
                        diffcult: "1",
                        detail: "一个很小，轻量且可完全扩展的API，用于控制几何图形的编辑。",
                        icon: "editable.png",
                        update: "最后更新时间：2018-05-12"
                    }, {
                        name: "leaflet.Toolbar",
                        file: "toolbar",
                        diffcult: "1",
                        detail: "用于leaflet地图灵活，可扩展的工具栏。",
                        icon: "toolbar.png",
                        update: "最后更新时间：2018-05-12"
                    }, {
                        name: "PathDrag",
                        file: "path_drag",
                        diffcult: "1",
                        detail: "将拖拽功能添加到leaflet路径。",
                        icon: "path_drag.png",
                        update: "最后更新时间：2018-05-12"
                    }, {
                        name: "字形标记",
                        file: "icon_glyph",
                        diffcult: "1",
                        detail: "将图标字体中的字形添加到您的leafletJS标记中。",
                        icon: "icon_glyph.png",
                        update: "最后更新时间：2018-05-12"
                    }, {
                        name: "leaflet.VectorGrid",
                        file: "vectorgrid",
                        diffcult: "1",
                        detail: "在leaflet上显示格网矢量数据。",
                        icon: "vectorgrid.png",
                        update: "最后更新时间：2018-05-12"
                    }]
                }
            ]
        },
        {
            name: "几何图元",
            materialicon: "bubble_chart",
            folder: "geometry",
            leaffolder: false,
            childs: [{
                name: "通用几何GeoJSON",
                materialicon: "bubble_chart",
                folder: "geojson",
                leaffolder: true,
                childs: [{
                    name: "Point",
                    file: "point",
                    diffcult: "1",
                    detail: "给定一个geojson格式的经纬坐标点，将其展示在leaflet上。",
                    icon: "point.png",
                    mardown: "E01GeoPoint.md",
                    update: "最后更新时间：2018-05-10"
                }, {
                    name: "Line",
                    file: "line",
                    diffcult: "1",
                    detail: "将地理位置的坐标数组(二维)以geojson格式加载进leaflet。",
                    icon: "line.png",
                    mardown: "E01GeoPoint.md",
                    update: "最后更新时间：2018-05-10"
                }, {
                    name: "Polygon",
                    file: "polygon",
                    diffcult: "1",
                    detail: "一个环形坐标数组的数组(三维)以geojson格式加载进leaflet。针对“带洞区”，最好采取外圈顺时针，内圈逆时针的方式",
                    icon: "polygon.png",
                    mardown: "E01GeoPoint.md",
                    update: "最后更新时间：2018-05-10"
                }, {
                    name: "MultiPoint",
                    file: "multipoint",
                    diffcult: "1",
                    detail: "将位置坐标组成二维数组以geojson格式加载进leafelt中。",
                    icon: "multipoint.png",
                    mardown: "E01GeoPoint.md",
                    update: "最后更新时间：2018-05-10"
                }, {
                    name: "MultiLine",
                    file: "multiline",
                    diffcult: "1",
                    detail: "将线坐标数组的数组(三维)以geojson格式加载进leaflet。",
                    icon: "multiline.png",
                    update: "最后更新时间：2018-05-10"
                }, {
                    name: "MultiPolygon",
                    file: "multipolygon",
                    diffcult: "2",
                    detail: "将面坐标数组的数组(四维)以geojson格式加载进leaflet。",
                    icon: "multipolygon.png",
                    update: "最后更新时间：2018-05-10"
                }, {
                    name: "FeatureCollection",
                    file: "featurecollection",
                    diffcult: "2",
                    detail: "以Geojson特征集合数据格式将数据加载进leaflet。",
                    icon: "featurecollection.png",
                    update: "最后更新时间：2018-05-10"
                }, {
                    name: "地理数据转换",
                    file: "transform",
                    diffcult: "2",
                    detail: "将特定或非特定格式的地理数据转换为标准的geojson格式加载进leaflet。",
                    icon: "transform.png",
                    update: "最后更新时间：2018-05-10"
                }, {
                    name: "JsonParse",
                    file: "jsonparse",
                    diffcult: "2",
                    detail: "接受一个标准格式的JSON字符串，并返回解析后标准的JavaScript对象，可用于geojson数据的解析。",
                    icon: "jsonparse.png",
                    update: "最后更新时间：2018-05-10"
                }]
            }]
        },
        {
            name: "客户端可视化",
            materialicon: "camera",
            folder: "dataview",
            leaffolder: false,
            childs: [{
                name: "通用可视化",
                materialicon: "camera",
                folder: "common",
                leaffolder: true,
                childs: [{
                    name: "注记动画",
                    file: "animatemarker",
                    diffcult: "1",
                    detail: "animatemarker",
                    icon: "animatemarker.png",
                    update: "最后更新时间：2018-07-25"
                }, {
                    name: "蚂蚁线",
                    file: "antpath",
                    diffcult: "1",
                    detail: "antpath",
                    icon: "antpath.png",
                    update: "最后更新时间：2018-07-25"
                }, {
                    name: "基本聚类",
                    file: "cluster_base",
                    diffcult: "1",
                    detail: "cluster_base",
                    icon: "cluster_base.png",
                    update: "最后更新时间：2018-07-25"
                }, {
                    name: "聚类事件",
                    file: "cluster_event",
                    diffcult: "1",
                    detail: "cluster_event",
                    icon: "cluster_event.png",
                    update: "最后更新时间：2018-07-25"
                }, {
                    name: "聚类属性",
                    file: "cluster_option",
                    diffcult: "1",
                    detail: "cluster_option",
                    icon: "cluster_option.png",
                    update: "最后更新时间：2018-07-25"
                }, {
                    name: "飞行动画",
                    file: "flightanimation",
                    diffcult: "1",
                    detail: "flightanimation",
                    icon: "flightanimation.png",
                    update: "最后更新时间：2018-07-25"
                }, {
                    name: "简单热力",
                    file: "heatersimple",
                    diffcult: "1",
                    detail: "heatersimple",
                    icon: "heatersimple.png",
                    update: "最后更新时间：2018-07-25"
                }, {
                    name: "图形脉冲",
                    file: "iconpulse",
                    diffcult: "1",
                    detail: "iconpulse",
                    icon: "iconpulse.png",
                    update: "最后更新时间：2018-07-25"
                }, {
                    name: "迁移图",
                    file: "migrate",
                    diffcult: "1",
                    detail: "migrate",
                    icon: "migrate.png",
                    update: "最后更新时间：2018-07-25"
                }, {
                    name: "真实标注移动",
                    file: "realmovemarker",
                    diffcult: "1",
                    detail: "realmovemarker",
                    icon: "realmovemarker.png",
                    update: "最后更新时间：2018-07-25"
                }]
            }, {
                name: "Mapv",
                materialicon: "camera",
                folder: "mapv",
                leaffolder: true,
                childs: [{
                    name: "DataSet",
                    file: "dataset",
                    diffcult: "1",
                    detail: "",
                    icon: "dataset.png",
                    update: "最后更新时间：2018-07-25"
                }, {
                    name: "Intensity",
                    file: "intensity",
                    diffcult: "1",
                    detail: "",
                    icon: "intensity.png",
                    update: "最后更新时间：2018-07-25"
                }, {
                    name: "Layer图层",
                    file: "layer",
                    diffcult: "1",
                    detail: "",
                    icon: "layer.png",
                    update: "最后更新时间：2018-07-25"
                }]
            }, {
                name: "D3",
                materialicon: "camera",
                folder: "d3",
                leaffolder: true,
                childs: [{
                    name: "csv格式-点CSS样式",
                    file: "csv",
                    diffcult: "2",
                    detail: "d3-swiss-cities简单示例针对csv，dsv等格式",
                    icon: "csv.png",
                    update: "最后更新时间：2018-07-25"
                }, {
                    name: "geojson-属性CSS样式",
                    file: "line",
                    diffcult: "2",
                    detail: "d3-例针对geojson等格式,按照属性分类设置样式",
                    icon: "line.png",
                    update: "最后更新时间：2018-07-25"
                }, {
                    name: "geojson格式-图层CSS样式",
                    file: "geojson",
                    diffcult: "2",
                    detail: "d3-针对geojson等格式,按照图层，图元分类过滤设置样式",
                    icon: "geojson.png",
                    update: "最后更新时间：2018-07-25"
                }, {
                    name: "蜂窝密度Hexbin",
                    file: "hexbin",
                    diffcult: "3",
                    detail: "d3-hexbin简单示例针对geojson,csv,tsv等格式,数据量大的时候请使用该方式",
                    icon: "hexbin.png",
                    update: "最后更新时间：2018-07-25，不懂请联系潘卓然"
                }, {
                    name: "统计专题图",
                    file: "choropleth",
                    diffcult: "3",
                    detail: "d3专题图示例针对geojson,csv,tsv等格式,数据量大的时候请使用该方式",
                    icon: "choropleth.png",
                    update: "最后更新时间：2018-07-25，不懂请联系潘卓然"
                }, {
                    name: "边界专题图",
                    file: "border",
                    diffcult: "3",
                    detail: "d3边界图示例针对geojson,csv,tsv等格式,数据量大的时候请使用该方式",
                    icon: "border.png",
                    update: "最后更新时间：2018-07-25，不懂请联系潘卓然"
                }, {
                    name: "动态专题图",
                    file: "timer ",
                    diffcult: "3",
                    detail: "d3动态专题图示例针对geojson,csv,tsv等格式,数据量大的时候请使用该方式",
                    icon: "timer.png",
                    update: "最后更新时间：2018-07-25，不懂请联系潘卓然"
                }, {
                    name: "交互操作Interactive",
                    file: "interactive",
                    diffcult: "3",
                    detail: "d3-交互操作简单示例，数据量大的时候请使用该方式",
                    icon: "interactive.png",
                    update: "最后更新时间：2018-07-25，不懂请联系潘卓然"
                }, {
                    name: "直方图",
                    file: "histogram",
                    diffcult: "1",
                    detail: "d3-常规直方图绘制",
                    icon: "histogram.png",
                    update: "最后更新时间：2018-07-25，不懂请联系潘卓然"
                }]
            }]
        },
        {
            name: "客户端空间分析",
            materialicon: "iso",
            folder: "analysis",
            leaffolder: true,
            childs: [{
                name: "缓冲区分析",
                file: "buffer",
                diffcult: "1",
                detail: "给定一个缓冲半径进行缓冲区分析. 单位支持 miles 米,kilometers 千米,degrees 度.",
                icon: "buffer.png",
                update: "最后更新时间：2018-05-05"
            }, {
                name: "泰森多边形分析",
                file: "voronoi",
                diffcult: "2",
                detail: "针对给定的点生成泰森多边形,请注意一定要传入外包矩形bbox参数",
                icon: "voronoi.png",
                update: "最后更新时间：2018-05-05"
            }, {
                name: "TIN三角网分析",
                file: "tin",
                diffcult: "1",
                detail: "TIN方法将无重复点的散乱数据点集按某种规则(如Delaunay 规则) 进行三角剖分，使这些散乱点形成连续但不重叠的不规则三角面片网，并以此来描述3D 物体的表面。",
                icon: "tin.png",
                update: "最后更新时间：2018-05-05"
            }, {
                name: "中心点提取",
                file: "centroid",
                diffcult: "1",
                detail: "计算给定GeoJSON的数据中心支持所有的GeoJSON类型",
                icon: "centroid.png",
                update: "最后更新时间：2018-05-05"
            }, {
                name: "插值分析",
                file: "along",
                diffcult: "1",
                detail: "线插值操作是通过 计算起点-终点长度,然后再根据长度等分计算需要插值的点,最后再把这些点插入到原始数据中.",
                icon: "along.png",
                update: "最后更新时间：2018-05-05"
            }]
        },
        {
            name: "矢量瓦片",
            materialicon: "layers",
            folder: "vectortile",
            leaffolder: true,
            childs: [{
                name: "基本介绍",
                file: "index",
                diffcult: "1",
                detail: "",
                icon: "index.gif",
                update: "最后更新时间：2018-06-27,如有问题请咨询创新中心"
            }, {
                name: "基本架构",
                file: "framework",
                diffcult: "2",
                detail: "",
                icon: "framework.gif",
                update: "最后更新时间：2018-06-27,如有问题请咨询创新中心"
            }, {
                name: "基本使用",
                file: "product",
                diffcult: "2",
                detail: "",
                icon: "product.gif",
                update: "最后更新时间：2018-06-27,如有问题请咨询创新中心"
            }, {
                name: "基本知识",
                file: "base",
                diffcult: "2",
                detail: "",
                icon: "base.gif",
                update: "最后更新时间：2018-06-27,如有问题请咨询创新中心"
            }, {
                name: "基本样式",
                file: "style",
                diffcult: "2",
                detail: "",
                icon: "style.gif",
                update: "最后更新时间：2018-06-27,如有问题请咨询创新中心"
            }, {
                name: "测试性能与效率",
                file: "effect",
                diffcult: "3",
                detail: "",
                icon: "effect.gif",
                update: "最后更新时间：2018-06-27,如有问题请咨询创新中心"
            }]
        },
        {
            name: "实时数据分析Els",
            materialicon: "search",
            folder: "elasticsearch",
            leaffolder: true,
            childs: [{
                name: "首页",
                file: "index",
                diffcult: "1",
                detail: "",
                icon: "index.gif",
                update: "最后更新时间：2018-06-27,如有问题请咨询创新中心"
            }, {
                name: "聚合",
                file: "base",
                diffcult: "2",
                detail: "",
                icon: "base.gif",
                update: "最后更新时间：2018-06-27,如有问题请咨询创新中心"
            }, {
                name: "聚合用例",
                file: "aggsexamples",
                diffcult: "2",
                detail: "",
                icon: "aggsexamples.gif",
                update: "最后更新时间：2018-06-27,如有问题请咨询创新中心"
            }, {
                name: "地图操作基本概念",
                file: "gisbase",
                diffcult: "2",
                detail: "",
                icon: "gisbase.gif",
                update: "最后更新时间：2018-06-27,如有问题请咨询创新中心"
            }, {
                name: "官方接口",
                file: "command",
                diffcult: "2",
                detail: "",
                icon: "command.gif",
                update: "最后更新时间：2018-06-27,如有问题请咨询创新中心"
            }, {
                name: "中地接口",
                file: "webclient",
                diffcult: "2",
                detail: "",
                icon: "webclient.gif",
                update: "最后更新时间：2018-06-27,如有问题请咨询创新中心"
            }]
        }
    ]
};