export const Leaflet = [
  {
    name: "leaflet-MarkerCluster",
    func: "为leaflet提供华丽的聚类动画标记功能。",
    dev: "需要leaflet1.0.0(leaflet0.4,0.5,0.7需下载相应兼容版本)",
    update: "2018/4/20",
    version: "v1.3.0/v1.3.0",
    licesen: "MIT License",
  },
  {
    name: "leaflet-Heat",
    func:
      "小巧、简单、快速的leaflet热力图插件,使用simpleheat引擎添加聚类点到格网中来提高性能。",
    dev: "需引入leaflet-heat.js脚本",
    update: "2016/9/30",
    version: "v0.2.0/v0.2.0",
    licesen: "BSD-2-Clause License",
  },
  {
    name: "leaflet-Draw",
    func: "leaflet的矢量绘制与编辑插件",
    dev: "需要引入L.Draw相应脚本，支持leaflet0.7.x和1.0.0+以上版本分支。",
    update: "	2018/3/18",
    version: "v0.4.14/v0.4.14",
    licesen: "MIT License",
  },
  {
    name: "leaflet-Editable",
    func: "在Leaflet中可编辑几何图形",
    dev: "需引入Leaflet.Editable.js和Path.Drag.js脚本",
    update: "2017/8/25",
    version: "v1.1.0/v1.1.0",
    licesen: "暂无",
  },
  {
    name: "leaflet-Fullscreen",
    func: "leaflet的全屏控制插件",
    dev: "需引入leaflet1.0以后的版本，更早的版本有可能不起作用",
    update: "2017/1/19",
    version: "v1.0.2/v1.0.2",
    licesen: "ISC License",
  },
  {
    name: "leaflet-Graticule",
    func:
      "创建一个Canvas作为ImageOverlay来绘制Lat/Lon Graticule，并在地图的边缘显示网格标签",
    dev: "需要引入leaflet脚本",
    update: "2016/10/20",
    version: "无说明",
    licesen: "暂无",
  },
  {
    name: "leaflet-IconGlyph",
    func: "将图标字体中的字形放入LeafletJS标记中",
    dev: "需引入Leaflet.Icon.Glyph.js脚本",
    update: "2016/4/27",
    version: "无说明",
    licesen: "暂无",
  },
  {
    name: "leaflet-Measurement",
    func: "用于测量点击点之间的真实距离和方位角",
    dev: "引入leaflet1.0.0以上版本以及leaflet-ruler.js脚本",
    update: "2017/7/30",
    version: "无说明",
    licesen: "MIT License",
  },
  {
    name: "leaflet-MousePosition",
    func: "Leaflet的鼠标位置插件",
    dev: "需引入leaflet脚本",
    update: "2013/7/19",
    version: "无说明",
    licesen: "MIT License",
  },
  {
    name: "leaflet-PathDrag",
    func: "将拖拽功能添加到Leaflet路径中",
    dev: "需引入Path.Drag.js脚本",
    update: "2017/8/9",
    version: "v0.0.6/v0.0.6",
    licesen: "暂无",
  },
  {
    name: "leaflet-Toolbar",
    func: "用于leaflet地图的灵活，可扩展的工具栏",
    dev: "需引入leaflet.toolbar.js脚本",
    update: "2017/11/1",
    version: "v0.3.0/v0.3.0",
    licesen: "MIT License",
  },
  {
    name: "leaflet-AwesomeMarkers",
    func: "	基于Font Awesome/Twitter Bootstrap图标的Leaflet彩色标记",
    dev: "需要引入相应的CSS以及JS脚本",
    update: "2017/11/4",
    version: "v2.0.2/v2.0.2",
    licesen: "MIT License",
  },
  {
    name: "leaflet-AnimatedMarker",
    func: "用于沿折线制作动画标记",
    dev: "该插件使用CSS3动画以特定速率移动标记，所以需要浏览器支持CSS3",
    update: "2017/4/19",
    version: "v1.0.0/v1.0.0",
    licesen: "MIT License",
  },
  {
    name: "leaflet-MigrationLayer",
    func: "用于显示迁移数据，如人口，航班，车辆，交通等。使地图上的数据可视化",
    dev:
      "支持Internet Explorer 10+、Google Chrome、Safari、Firefox浏览器，同时需引入leaflet.migrationLayer.js脚本",
    update: "2017/10/9",
    version: "暂无",
    licesen: "MIT License",
  },
  {
    name: "leaflet-MovingMarker",
    func: "创建移动标记的Leaflet插件",
    dev:
      "这个插件通过Leaflet L.Util.requestAnimFrame方法在内部使用，需引入MovingMarker.js脚本",
    update: "2015/11/17",
    version: "暂无",
    licesen: "暂无",
  },
  {
    name: "leaflet-AntPath",
    func: "用“蚂蚁路径”动画通量创建leaflet多段线",
    dev: "需要leaflet1.0.0以上版本",
    update: "2018/5/8",
    version: "v1.1.1/v1.1.1",
    licesen: "MIT License",
  },
  {
    name: "leaflet-minimap",
    func: "leaflet的鹰眼地图",
    dev: "需要leaflet0.7.7以上版本",
    update: "2018/3/2	",
    version: "暂无",
    licesen: "BSD-2-Clause License",
  },
  {
    name: "leaflet.ChineseTmsProviders",
    func:
      "leaflet的常用中国地图,以上所有地图都使用坐标参考系统（CRS）是EPSG：3857，web墨卡托投影",
    dev: "需要leaflet0.7.7以上版本",
    update: "2018/4/18",
    version: "暂无",
    licesen: "暂无",
  },
  {
    name: "Leaflet.MagnifyingGlass",
    func: "leaflet的地图探查功能",
    dev: "需要leaflet0.7.2以上版本",
    update: "2018/1/13",
    version: "暂无",
    licesen: "MIT License",
  },
  {
    name: "Leaflet.OpacityControls",
    func: "leaflet的透明度控制功能",
    dev: "无明确版本要求说明",
    update: "2014/9/13",
    version: "暂无",
    licesen: "BSD-3-Clause License",
  },
  {
    name: "Leaflet.PolylineDecorator",
    func: "leaflet的箭头线型功能",
    dev: "需要leaflet0.7.2以上版本",
    update: "2018/1/28",
    version: "暂无",
    licesen: "MIT License",
  },
  {
    name: "leaflet-measure",
    func: "leaflet的测量控件功能",
    dev: "无明确版本要求说明",
    update: "2018/4/9",
    version: "暂无",
    licesen: "BSD-3-Clause License",
  },
  {
    name: "Leaflet-WFST",
    func: "leaflet的OGC-WFS要素类功能",
    dev: "无明确版本要求说明",
    update: "2017/10/24",
    version: "暂无",
    licesen: "MIT License",
  },
  {
    name: "heatmapjs",
    func: "leaflet的heatmapjs的热力实现",
    dev: "无明确版本要求说明",
    update: "非开源，未说明",
    version: "非开源，未说明",
    licesen: "非开源，未说明",
  },
  {
    name: "Leaflet.Polyline.SnakeAnim",
    func: "leaflet的路线轨迹动画功能",
    dev: "需要leaflet1.0.0以上版本",
    update: "2015/12/11",
    version: "暂无",
    licesen: "暂无",
  },
  {
    name: "leaflet-icon-pulse",
    func: "leaflet的icon动画效果",
    dev: "需要leaflet0.7.0以上版本",
    update: "2017/9/6",
    version: "暂无",
    licesen: "暂无",
  },
  {
    name: "Echarts 4.0",
    func: "百度Echarts-4.0",
    dev: "4.0",
    update: "2018-07-23",
    version: "4.0",
    licesen: "MIT License",
  },
  {
    name: "MapV 2.0",
    func: "百度Mapv-2.0",
    dev: "2.0",
    update: "2018-07-23",
    version: "2.0",
    licesen: "MIT License",
  },
];

export const MapboxGL = [
  {
    name: "mapbox-gl-compare",
    func: "为mapboxgl提供卷帘对比功能",
    dev: "无版本要求",
    update: "2017/3/1",
    version: "v0.1.0",
    licesen: "ISC License",
  },
  {
    name: "mapbox-gl-draw",
    func: "为mapboxgl提供绘制功能",
    dev: "无版本要求",
    update: "	2018/6/3",
    version: "v1.0.9",
    licesen: "ISC License",
  },
  {
    name: "mapbox-gl-language",
    func: "为mapboxgl提供语言切换功能",
    dev: "无版本要求",
    update: "2018/3/23",
    version: "v0.9.2",
    licesen: "ISC License",
  },
  {
    name: "FileSaver.js",
    func: "	为mapboxgl提供导出图片功能",
    dev: "无版本要求",
    update: "2018/3/23",
    version: "v0.9.2",
    licesen: "暂无",
  },
  {
    name: "jsPDF",
    func: "为mapboxgl提供导出PDF功能",
    dev: "无版本要求",
    update: "2018/6/13",
    version: "master",
    licesen: "MIT License",
  },
  {
    name: "Echarts 4.0",
    func: "百度Echarts-4.0",
    dev: "4.0",
    update: "2018-07-23",
    version: "4.0",
    licesen: "MIT License",
  },
  {
    name: "MapV 2.0",
    func: "百度Mapv-2.0",
    dev: "2.0",
    update: "2018-07-23",
    version: "2.0",
    licesen: "MIT License",
  },
];

export const OpenLayers = [
  {
    name: "ol-mapbox-style",
    func: "为openlayers提供矢量瓦片绘制功能",
    dev: "ol5以上",
    update: "2020/3/1",
    version: "v6.1.2",
    licesen: "BSD 2-Clause",
  },
];

export const Cesium = [
  {
    name: "Echarts 4.0",
    func: "百度Echarts-4.0",
    dev: "4.0",
    update: "2018-07-23",
    version: "4.0",
    licesen: "MIT License",
  },
  {
    name: "MapV 2.0",
    func: "百度Mapv-2.0",
    dev: "2.0",
    update: "2018-07-23",
    version: "2.0",
    licesen: "MIT License",
  },
];
